version: '3.1'
name: "bugtracker"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $${docker.admin.username}
      POSTGRES_PASSWORD: $${docker.admin.password}
      POSTGRES_DB: bugtracker
    ports:
      - "5432:5432"
    env_file:
      - security.env